on:
  push:
    branches:    
      - master
name: CI
jobs:
  test:
    name: CI
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=12.4,name=iPhone X']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Carthage and Build
        run: |
          cd IDDog
          carthage update --platform iOS --no-use-binaries
        env: 
         destination: ${{ matrix.destination }}
