on:
  push:
    branches:    
      - master
name: CI
jobs:
  test:
    name: CI
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=13.1,name=iPhone 11']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Carthage, Build and Test
        run: |
          cd IDDog
          carthage update --platform iOS --no-use-binaries
          xcodebuild clean build test -project IDDog.xcodeproj -scheme IDDog -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
